"models:
  baseline:
    n_estimators: 50
    max_depth: 10
    data_version: v1
  improved:
    n_estimators: 100
    max_depth: 20
    data_version: v2

data:
  raw_path: data/raw/
  processed_path: data/processed/" | Out-File -FilePath "ml/configs/params.yaml" -Encoding utf8
